spring:
  application:
    name: chat
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false # 개발 중 캐싱 비활성화
  resources:
    static-locations: classpath:/static/
    cache-period: 3600 # 정적 리소스 캐싱 기간 (초 단위)
  websocket:
    enabled: true
server:
  port: 8080 # 서버 포트 설정
logging:
  level:
    org.springframework: INFO
    com.yourapp: DEBUG # 필요에 따라 로깅 레벨 조정
